# render.yaml
services:
  - type: web
    name: nextcut-backend-v2
    env: node
    buildCommand: |
      npm install
      npm install --save-dev @types/node @types/express @types/cors @types/bcrypt @types/jsonwebtoken
      npx prisma generate
      npm run build
    startCommand: npm start
    healthCheckPath: /health
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
    scaling:
      minInstances: 1
      maxInstances: 3
